
title: Alvin's Individual Github Pages
description: >- # this means to ignore newlines until "baseurl:"
  CSA Tri-3 individual documentation, and project descriptions.

theme: minima
plugins:
  - jekyll-feed

baseurl: /CSA-Data-Structures
url: https://alvinzhengq.github.io
